name: linter-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          python -m pip install poetry
          make install

      - name: Lint the package
        run : |
            make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ 87b80a3b940d7a0f09bef11bbf864dfc357f674e22bd8a937d0b091c8a89c321 }}
        with:
          coverageCommand: make test
          debug: true
